version: "3"
services: 
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - "./mongodb-data:/data/db"
    networks:
      - mongo-go
    ports:
      - 27017:27017
      - 28017:28017
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  mongo-go: 
volumes:
  mongodb-data: