// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Lyric struct {
	ID      *string `json:"id"`
	Likes   *int    `json:"likes"`
	Content *string `json:"content"`
	Song    *Song   `json:"song"`
}

type Song struct {
	ID     *string  `json:"id"`
	Title  *string  `json:"title"`
	Lyrics []*Lyric `json:"lyrics"`
}
